version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
        environment:
          TZ: "Europe/Kiev"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run phase 1/2 tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml ./tests

      - run:
          name: run tests ui tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml ./tests/web_ui_test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports