version: 2.1

orbs:
  allure: ayte/allure@0.1.2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
        environment:
          TZ: "Europe/Kiev"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run phase 1/2 tests
          command: |
            . venv/bin/activate
            pytest --alluredir ./allure-results ./tests

      - allure/install:
          version: 2.12
          when: always

      - allure/report:
          when: always

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports