version: 2.1

orbs:
  allure: ayte/allure@0.1.2

jobs:
  build:
    parameters:
      build_allure_report:
        type: boolean
        default: true

    docker:
      - image: circleci/python:3.7.3-stretch-browsers
        environment:
          TZ: "Europe/Kiev"

    working_directory: ~/repo

    steps:
      - checkout

      - allure/install:
          version: '2.12'

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run phase 1/2 tests
          halt_build_on_fail: false
          command: |
            . venv/bin/activate
            pytest --alluredir ./allure-results ./tests

      - when:
          condition: << parameters.build_allure_report >>
          steps:
            - allure/report:
                results-path: './allure-results'